
name: TID-ID Smartsheets Applications
on: [push]

jobs:

# ----------------------------------------------------------------------------

  gen_release:
    uses: slaclab/ruckus/.github/workflows/gen_release.yml@main
    with:
      version: '1.0.0'
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

# ----------------------------------------------------------------------------
