name: Deployment

on:
  release:
    types:
      - created

jobs:

  win_packager:
    name: Package Windows Binary
    runs-on: windows-latest
    steps:

      # This step checks out a copy of your repository.
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install sip pyqt5 pyinstaller smartsheet-python-sdk

      - name: Get Image Information
        id: get_image_info
        run: |
          echo ::set-output name=tag::`git describe --tags`

      - name: Build
        env:
          IMAGE_VER: ${{ steps.get_image_info.outputs.tag }}
          GH_REPO_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pyinstaller --onefile check_project_gui.py

      - name: Upload
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist\check_project_gui.exe
          asset_name: check_project_gui.exe
          asset_content_type: binary/octet-stream

  mac_packager:
    name: Package MacOS Binary
    runs-on: macos-10.15
    steps:

      # This step checks out a copy of your repository.
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install sip pyqt5 pyinstaller smartsheet-python-sdk

      - name: Get Image Information
        id: get_image_info
        run: |
          echo ::set-output name=tag::`git describe --tags`

      - name: Build
        env:
          IMAGE_VER: ${{ steps.get_image_info.outputs.tag }}
          GH_REPO_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pyinstaller --onefile check_project_gui.py

      - name: Upload
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/check_project_gui
          asset_name: check_project_gui_osx
          asset_content_type: binary/octet-stream

  linux_packager:
    name: Package Linux Binary
    runs-on: ubuntu-18.04
    steps:

      # This step checks out a copy of your repository.
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install sip pyqt5 pyinstaller smartsheet-python-sdk

      - name: Get Image Information
        id: get_image_info
        run: |
          echo ::set-output name=tag::`git describe --tags`

      - name: Build
        env:
          IMAGE_VER: ${{ steps.get_image_info.outputs.tag }}
          GH_REPO_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pyinstaller --onefile check_project_gui.py

      - name: Upload
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/check_project_gui
          asset_name: check_project_gui_linux
          asset_content_type: binary/octet-stream

